# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

target ‘MMForecastPlus’ do

pod 'SVProgressHUD'
pod 'THProgressView'
pod 'XMLDictionary'
pod 'SDWebImage', '~>3.7'

end

